version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=books_db
    ports:
      - "5432:5432"
    expose:
      - 5432
  redis:
    image: redis:6.0.5-alpine
    restart: always
    ports:
      - "6379:6379"
    expose:
      - 6379
    command: sh -c "redis-server && redis-cli monitor"
volumes:
  local_postgres_data:
