version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "80:8000"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=juan
      - POSTGRES_PASSWORD=peres
      - POSTGRES_DB=test
    ports:
      - "2345:5432"
    expose:
      - 2345
volumes:
  local_postgres_data:
