# Generated by Django 3.0.2 on 2020-01-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
